name: Test deploy go service to Nucleus
on:
  workflow_dispatch:
    inputs:
      nucleus_environment:
        description: 'Nucleus environment to deploy to stage or prod'
        type: string
        required: true
      deploy_environment:
        description: 'Environment to deploy service to'
        type: string
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "${{ inputs.nucleus_environment == 'stage' }}""
    steps:
      - uses: actions/checkout@v3
      - name: set nucleus debug env
        id: debug
        run: |
          echo "NUCLEUS_DEBUG_ENV=stage" >> $GITHUB_ENV
      - name: Download Nucleus CLI & Login
        uses: nucleuscloud/setup-nucleus-cli-action@v1
        with:
          client_id: ${{ secrets.STAGE_E2E_TEST_CLIENT_ID }}
          client_secret: ${{ secrets.STAGE_E2E_TEST_CLIENT_SECRET }}
      - uses: nucleuscloud/deploy-action@v1
        working-directory: ./go
        with:
          environment: ${{ inputs.deploy_environment }}
    if: "${{ inputs.nucleus_environment == 'production' }}"
    steps:
      - uses: actions/checkout@v3
      - name: Download Nucleus CLI & Login
        uses: nucleuscloud/setup-nucleus-cli-action@v1
        with:
          client_id: ${{ secrets.PROD_E2E_TEST_CLIENT_ID }}
          client_secret: ${{ secrets.PROD_E2E_TEST_CLIENT_SECRET }}
      - uses: nucleuscloud/deploy-action@v1
        working-directory: ./go
        with:
          environment: ${{ inputs.deploy_environment }}
